### ISSUE TITLE
Duping issue?

### ISSUE THREAD

**Issue by AdamDAuria** [CodedRed-Spigot/SafeDrop#5] opened 2023-10-11 02:50 UTC
Their was a Duping issue maybe  found on your guys plugin 

[video demonstration](https://drive.google.com/file/d/1wSaWPryOCC-QfjJIgMm2lDan9JqDk0FZ/view?usp=sharing)

**Comment by CodedRedGIT** [comment] 2023-10-11 04:20
Thanks for reporting, I will be taking a look at this tomorrow afternoon!

**Comment by CodedRedGIT** [comment] 2023-10-11 04:23
In the meanwhile, if you could provide more information about your server that would be a big help!
- What server version are you using?
- Are you using the latest version of SafeDrop?
- Are you using any other plugins that control dropping items? Any custom item plugins? Any region plugins, like worldguard?

**Comment by CodedRedGIT** [comment] 2023-10-11 18:20
I attempted to recreate this issue numerous times but was unable to reproduce it. If you could provide more information, that would be helpful. Additionally, please try using the latest version of the plugin, which was updated today: https://www.spigotmc.org/resources/safedrop-safely-drop-items.72585/update?update=519698.

**Comment by MinerCoffee** [comment] 2023-10-14 15:25
Hey CodedRedGit! I can confirmed it dupes in gamemode creative while droping it. The plugin version is 1.2.2 amd the server version is 1.20.1

**Comment by CodedRedGIT** [comment] 2023-10-15 00:34
> Hey CodedRedGit! I can confirmed it dupes in gamemode creative while droping it. The plugin version is 1.2.2 amd the server version is 1.20.1

Thank you, I will work on a fix for this!

**Comment by CodedRedGIT** [comment] 2023-12-15 20:12
Resolved in the latest update.

**Closed by CodedRedGIT** 2023-12-15 20:12 UTC
Labels: question
